name: Apply

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    env:
      TF_VAR_rds_admin: ${{ vars.TF_VAR_RDS_ADMIN }}
      TF_VAR_rds_admin_password: ${{ vars.TF_VAR_RDS_ADMIN_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Modify to your desired AWS region

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Capture RDS Endpoint
        id: curiousjcdb_endpoint
        run: |
          endpoint=$(terraform output -json curiousjcdb_endpoint)
          echo "curiousjcdb_endpoint=$endpoint" >> $GITHUB_OUTPUT
        working-directory: terraform

      - name: Echo RDS Endpoint
        run: echo "${{ steps.curiousjcdb_endpoint.outputs.curiousjcdb_endpoint }}"
        working-directory: terraform
